#SPDX-License-Identifier: MIT-0
---
# tasks file for ovirtopol

- name: Create a Temporary Working Directory
  ansible.builtin.file:
    path: '/var/tmp/ovirtopoloy-{{ ansible_date_time.date }}'
    state: directory
    mode: '0755'

- name: Copy Execution Files
  ansible.builtin.copy:
    src: kvmoverview.py
    dest: "/var/tmp/ovirtopoloy-{{ ansible_date_time.date }}/kvmoverview.py"
    mode: '0755'

- name: Execute Script
  ansible.builtin.command: 
    cmd: "python /var/tmp/ovirtopoloy-{{ ansible_date_time.date }}/kvmoverview.py"
  args:
    chdir: "/var/tmp/ovirtopoloy-{{ ansible_date_time.date }}/"

- ansible.builtin.debug:
    msg: /var/tmp/ovirtopoloy-{{ ansible_date_time.date }}

- name: Catch Output File name
  ansible.builtin.shell: "ls /var/tmp/ovirtopoloy-{{ ansible_date_time.date }} | grep json"
  register: kvm_output_name

- name: Copy the json Output File
  ansible.builtin.fetch:
    src: "/var/tmp/ovirtopoloy-{{ ansible_date_time.date }}/{{ kvm_output_name.stdout }}"
    dest: "{{ hostvars['localhost']['local_dir'] }}/{{ kvm_output_name.stdout }}"
    flat: yes

- name: Cleanup old ovirtopoloy files
  ansible.builtin.file:
    path: "/var/tmp/ovirtopoloy-{{ ansible_date_time.date }}/"
    state: absent
